[phases.setup]
nixPkgs = ["nodejs-16_x", "nodejs-default"]

[phases.install]
cmds = [
    "npm install"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
