[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install] 
cmds = [
  'cd services/main-api',
  'python3 -m pip install -r requirements.txt'
]

[phases.build]
cmds = ['cd services/main-api']

[start]
cmd = 'cd services/main-api && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT'

[variables]
PYTHONPATH = '/app/services/main-api'
PYTHONUNBUFFERED = '1'
